stages:
- test
- deploy

sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml

lint chart:
  image:
    name: alpine/helm:3.11.2
  stage: test
  script:
    - lint .

package chart:
  dependencies:
    - lint chart
  image:
    name: alpine/helm:3.11.2
#    entrypoint:
#      - /bin/bash
#      - -c
  stage: deploy
  script:
    - package . -u
#    - export ARTIFACT=$(find . -type f -iname "*.tgz" | cut -c3-)
  artifacts:
    name: chart.tgz
    paths:
      - ./*.tgz

deploy chart:
  dependencies:
    - package chart
  image:
    name: curlimages/curl:8.00.1
  stage: deploy
  script:
    - 'curl --request POST --user gitlab-ci-token:$CI_JOB_TOKEN --form "chart=@chart.tgz" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/helm/api/stable/charts"'
