stages:
- test
- package
- deploy

sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml

lint chart:
  image:
    name: alpine/helm:3.11.2
    entrypoint:
      - /bin/bash
      - -c
  stage: test
  script:
    - helm lint .

package chart:
  dependencies:
    - lint chart
  image:
    name: alpine/helm:3.11.2
    entrypoint:
      - /bin/bash
      - -c
  stage: package
  script:
    - helm package . -u
  artifacts:
    expire_in: 3 mins
    paths:
      - ./*.tgz

deploy chart:
  dependencies:
    - package chart
  image:
    name: curlimages/curl:8.00.1
  stage: deploy
  script:
    - ls -lrt
    - export ARTIFACT=$(find . -type f -iname "*.tgz" | cut -c3-)
    - echo $ARTIFACT
    - 'curl --request POST --user gitlab-ci-token:$CI_JOB_TOKEN --form "chart=@$ARTIFACT" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/helm/api/stable/charts"'
