apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jdownloader2-headless.fullname" . }}-secret
type: Opaque
data:
  email: {{ .Values.server.email | b64enc }}
  password: {{ .Values.server.password | b64enc }}