{{- if .Values.service.web.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "jdownloader2-headless.fullname" . }}-web
  labels:
    {{- include "jdownloader2-headless.labels" . | nindent 4 }}
spec:
  {{- if and .Values.ingress.enabled }}
  type: ClusterIP
  {{- else }}
  type: {{ .Values.service.web.type }}
  {{- end }}
  ports:
    - port: {{ .Values.service.web.port }}
      targetPort: web
      protocol: TCP
      name: web
  selector:
    {{- include "jdownloader2-headless.selectorLabels" . | nindent 4 }}
{{- end }}
