name: unittest

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    container: alpine/helm:3.11.3
    steps:
      - uses: actions/checkout@v3
      - name: Install unittest bin
        run: helm plugin install https://github.com/helm-unittest/helm-unittest.git

      - name: Run unittest
        run: helm unittest .
